import React from 'react';
import {
    MDBBtn,
    MDBContainer,
    MDBRow,
    MDBCol,
    MDBCard,
    MDBCardBody,
    MDBCardImage,
    MDBInput,
    MDBIcon,
    MDBCheckbox,
    MDBTable
}
    from 'mdb-react-ui-kit';
import myImage from '../../assets/logo_.png';

import { NavLink } from 'react-router-dom';
import { useAppContextDept } from '../../Context/Context';

import NavBar from '../../Components/NavBar';

function RegisterDept() {


    const { stateDept, dispatchDept } = useAppContextDept();

    const handleNameChange = (e) => {
        // alert(e.target.value);
        // alert(stateDept.name);
        dispatchDept({ type: 'SET_deptName', payload: e.target.value });
    };
  
   
  
  




    const handleSubmit = async () => {
        console.log(stateDept);


        // const { stateDept } = useAppContext();

        try {
            const URL='http://localhost:9090/api/department/';
            
          const response = await fetch(URL, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(stateDept), // Send the form data as JSON
          });
    
          if (response.ok) {
            // Handle a successful response from the server
            console.log('Data sent successfully');
            console.log(stateDept);
            console.log(response);
            alert("Department created successfully");

          } else {
            // Handle errors from the server
            console.error('Error sending data to the server');
          }
        } catch (error) {
          console.error('An error occurred while sending data:', error);
        }
      };


    return (
        <>
        <NavBar></NavBar>
        <MDBContainer fluid>
        <NavLink to="/registeremp">   <button type="button" class="btn btn-danger" >Go To Department form</button></NavLink>

<NavLink to="/getalldept">   <button type="button" class="btn btn-info" >Get All Dept</button></NavLink>



            <MDBCard className='text-black m-5' style={{ borderRadius: '25px' }}>
                <MDBCardBody>
                    <MDBRow>
                        <MDBCol md='10' lg='6' className='order-2 order-lg-1 d-flex flex-column align-items-center'>

                            <span className="h1 fw-bold mb-0">Register Department</span>
                            <br></br>
                            
<MDBContainer>
    <MDBTable> 
        <tr>
            <th>Department ID</th>
        </tr>
        <tr>
            <td>1</td>
            <td>IT</td>
        </tr>
        <tr><td>2
            </td>
            <td>HR</td>
        </tr>

        <tr><td>3
            </td>
            <td>Sales</td>
        </tr>

        <tr><td>4
            </td>
            <td>Finance</td>
        </tr>
            </MDBTable>
</MDBContainer>
                           


<h6>ID is Autogenerated</h6>


                            <div className="d-flex flex-row align-items-center mb-4">
                                <MDBIcon fas icon="envelope me-3" size='lg' />
                                <MDBInput label='Name' id='form2' type='text' value={stateDept.name} onChange={handleNameChange}
/>
                            </div>


<button type="button" class="btn btn-success" onClick={handleSubmit}>Create Dept</button>


                        </MDBCol>

                        <MDBCol md='10' lg='6' className='order-1 order-lg-2 d-flex align-items-center'>
                            <MDBCardImage src={myImage} fluid />

                        </MDBCol>

                    </MDBRow>
                </MDBCardBody>
            </MDBCard>

        </MDBContainer>

        </>
    );
}

export default RegisterDept;